-- DWM R2025b subsystem catalog, schema 2.
PRAGMA foreign_keys=OFF;
PRAGMA journal_mode=DELETE;
PRAGMA user_version=2;
BEGIN TRANSACTION;
CREATE TABLE block_products(block_id INTEGER NOT NULL REFERENCES blocks(id), product_code TEXT NOT NULL REFERENCES products(code), relationship TEXT NOT NULL DEFAULT 'library_owner_or_alternative' CHECK(relationship IN ('library_owner_or_alternative','assignment_requires_verification')), PRIMARY KEY(block_id,product_code));
INSERT INTO "block_products" VALUES(1,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(2,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(3,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(4,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(5,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(6,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(7,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(8,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(9,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(10,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(11,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(12,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(13,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(14,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(15,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(16,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(17,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(18,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(19,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(20,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(21,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(22,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(23,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(24,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(25,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(26,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(27,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(28,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(29,'SF','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(30,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(31,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(32,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(33,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(34,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(35,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(36,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(37,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(38,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(39,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(40,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(41,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(42,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(43,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(44,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(45,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(46,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(47,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(48,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(49,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(50,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(51,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(52,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(53,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(54,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(55,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(56,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(57,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(58,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(59,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(60,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(61,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(62,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(63,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(64,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(65,'DL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(66,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(67,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(68,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(69,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(70,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(71,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(72,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(73,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(74,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(75,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(76,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(77,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(78,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(79,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(80,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(81,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(82,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(83,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(84,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(85,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(86,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(87,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(88,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(89,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(90,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(91,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(92,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(93,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(94,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(95,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(96,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(97,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(98,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(99,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(100,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(101,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(102,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(103,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(104,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(105,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(106,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(107,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(108,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(109,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(110,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(111,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(112,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(113,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(114,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(115,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(116,'FL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(117,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(118,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(119,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(120,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(121,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(122,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(122,'BAT','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(123,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(123,'BAT','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(124,'BAT','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(125,'EE','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(126,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(127,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(128,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(129,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(130,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(131,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(132,'SC','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(133,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(134,'MB','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(135,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(136,'SL','library_owner_or_alternative');
INSERT INTO "block_products" VALUES(137,'SL','library_owner_or_alternative');
CREATE TABLE block_sources(block_id INTEGER NOT NULL REFERENCES blocks(id), source_id INTEGER NOT NULL REFERENCES sources(id), PRIMARY KEY(block_id,source_id));
INSERT INTO "block_sources" VALUES(2,1);
INSERT INTO "block_sources" VALUES(3,2);
INSERT INTO "block_sources" VALUES(4,3);
INSERT INTO "block_sources" VALUES(5,4);
INSERT INTO "block_sources" VALUES(6,5);
INSERT INTO "block_sources" VALUES(7,6);
INSERT INTO "block_sources" VALUES(8,7);
INSERT INTO "block_sources" VALUES(9,8);
INSERT INTO "block_sources" VALUES(10,8);
INSERT INTO "block_sources" VALUES(11,9);
INSERT INTO "block_sources" VALUES(59,10);
INSERT INTO "block_sources" VALUES(63,11);
INSERT INTO "block_sources" VALUES(65,12);
INSERT INTO "block_sources" VALUES(66,13);
INSERT INTO "block_sources" VALUES(74,14);
INSERT INTO "block_sources" VALUES(54,15);
INSERT INTO "block_sources" VALUES(79,16);
INSERT INTO "block_sources" VALUES(85,17);
INSERT INTO "block_sources" VALUES(83,18);
INSERT INTO "block_sources" VALUES(82,19);
INSERT INTO "block_sources" VALUES(96,20);
INSERT INTO "block_sources" VALUES(84,21);
INSERT INTO "block_sources" VALUES(99,22);
INSERT INTO "block_sources" VALUES(109,23);
INSERT INTO "block_sources" VALUES(110,24);
INSERT INTO "block_sources" VALUES(111,25);
INSERT INTO "block_sources" VALUES(114,26);
INSERT INTO "block_sources" VALUES(115,27);
INSERT INTO "block_sources" VALUES(116,28);
INSERT INTO "block_sources" VALUES(122,29);
INSERT INTO "block_sources" VALUES(123,30);
INSERT INTO "block_sources" VALUES(124,31);
INSERT INTO "block_sources" VALUES(125,32);
CREATE TABLE blocks(id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, target_release TEXT NOT NULL DEFAULT 'R2025b', availability_status TEXT NOT NULL DEFAULT 'candidate_not_individually_release_verified', runtime_tested INTEGER NOT NULL DEFAULT 0 CHECK(runtime_tested IN (0,1)), introduced_release TEXT, notes TEXT NOT NULL DEFAULT '', entry_type TEXT NOT NULL DEFAULT 'component' CHECK(entry_type IN ('component','assembly')), classification_basis TEXT NOT NULL DEFAULT 'dwm_functional_boundary_v1', classification_rationale TEXT NOT NULL DEFAULT 'Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(1,'DC Motor','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete motor/generator combining electromagnetic and mechanical elements, such as windings, rotor and stator.');
INSERT INTO "blocks" VALUES(2,'BLDC','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete motor/generator combining electromagnetic and mechanical elements, such as windings, rotor and stator.');
INSERT INTO "blocks" VALUES(3,'PMSM','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete motor/generator combining electromagnetic and mechanical elements, such as windings, rotor and stator.');
INSERT INTO "blocks" VALUES(4,'Stepper Motor','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete motor/generator combining electromagnetic and mechanical elements, such as windings, rotor and stator.');
INSERT INTO "blocks" VALUES(5,'Induction Machine Squirrel Cage','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete motor/generator combining electromagnetic and mechanical elements, such as windings, rotor and stator.');
INSERT INTO "blocks" VALUES(6,'H-Bridge','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete power-conversion circuit containing or abstracting multiple switching and energy-transfer elements.');
INSERT INTO "blocks" VALUES(7,'Converter (Three-Phase)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete power-conversion circuit containing or abstracting multiple switching and energy-transfer elements.');
INSERT INTO "blocks" VALUES(8,'Average-Value Voltage Source Converter (Three-Phase)','R2025b','introduced_by_R2025b_documented',0,'R2018a','ENA enable/disable port and rectifier conduction-loss feature are R2026a additions; exclude them from R2025b models.','assembly','dwm_functional_boundary_v1','Represents a complete power-conversion circuit containing or abstracting multiple switching and energy-transfer elements.');
INSERT INTO "blocks" VALUES(9,'BLDC Commutation Logic','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(10,'BLDC Current Controller','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Combines proportional/integral and optional derivative control functions; classified as a functional control assembly, even if a selected configuration disables a term.');
INSERT INTO "blocks" VALUES(11,'BLDC Current Controller with PWM Generation','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Combines current regulation and PWM generation into one control assembly.');
INSERT INTO "blocks" VALUES(12,'PID Controller','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Combines proportional/integral and optional derivative control functions; classified as a functional control assembly, even if a selected configuration disables a term.');
INSERT INTO "blocks" VALUES(13,'DC Voltage Source','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(14,'Buck Converter','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete power-conversion circuit containing or abstracting multiple switching and energy-transfer elements.');
INSERT INTO "blocks" VALUES(15,'Boost Converter','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete power-conversion circuit containing or abstracting multiple switching and energy-transfer elements.');
INSERT INTO "blocks" VALUES(16,'Buck-Boost Converter','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete power-conversion circuit containing or abstracting multiple switching and energy-transfer elements.');
INSERT INTO "blocks" VALUES(17,'Controlled Voltage Source','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(18,'Controlled Current Source','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(19,'Resistor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(20,'Capacitor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(21,'Inductor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(22,'Ideal Transformer','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(23,'Discrete PID Controller','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Combines proportional/integral and optional derivative control functions; classified as a functional control assembly, even if a selected configuration disables a term.');
INSERT INTO "blocks" VALUES(24,'Discrete-Time Integrator','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(25,'Unit Delay','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(26,'Zero-Order Hold','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(27,'Rate Transition','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(28,'MATLAB Function','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','One user-defined computational component; reclassify a concrete implementation if it represents a combined subsystem.');
INSERT INTO "blocks" VALUES(29,'Chart','R2025b','candidate_not_individually_release_verified',0,NULL,'Called Stateflow Chart in the conversation; Chart is the block label.','component','dwm_functional_boundary_v1','One state-machine logic component; no particular multi-function controller architecture is specified.');
INSERT INTO "blocks" VALUES(30,'Ideal Rotational Motion Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(31,'Ideal Translational Motion Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(32,'Ideal Torque Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(33,'Ideal Force Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(34,'Voltage Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(35,'Current Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(36,'Temperature Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(37,'Transform Sensor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(38,'Quantizer','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(39,'Transport Delay','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(40,'Band-Limited White Noise','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(41,'Gain','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(42,'Bias','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(43,'Relational Operator','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(44,'Logical Operator','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(45,'Relay','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(46,'Switch','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(47,'Assertion','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(48,'Inertia','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(49,'Rotational Spring','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(50,'Rotational Damper','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(51,'Rotational Friction','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(52,'Revolute Joint','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(53,'Bushing Joint','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(54,'Flexible Cylindrical Beam','R2025b','introduced_by_R2025b_documented',0,'R2020a','','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(55,'Simple Gear','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents interacting transmission elements, such as a gear pair, planetary set, belt and pulleys, or screw and nut.');
INSERT INTO "blocks" VALUES(56,'Planetary Gear','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents interacting transmission elements, such as a gear pair, planetary set, belt and pulleys, or screw and nut.');
INSERT INTO "blocks" VALUES(57,'Worm and Gear','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents interacting transmission elements, such as a gear pair, planetary set, belt and pulleys, or screw and nut.');
INSERT INTO "blocks" VALUES(58,'Rack & Pinion','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents interacting transmission elements, such as a gear pair, planetary set, belt and pulleys, or screw and nut.');
INSERT INTO "blocks" VALUES(59,'Belt Drive','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents interacting transmission elements, such as a gear pair, planetary set, belt and pulleys, or screw and nut.');
INSERT INTO "blocks" VALUES(60,'Belt Pulley','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','One pulley/interface component; distinguish from the complete Belt Drive assembly.');
INSERT INTO "blocks" VALUES(61,'Disk Friction Clutch','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a friction mechanism combining interacting surfaces and actuation/load transfer.');
INSERT INTO "blocks" VALUES(62,'Disk Brake','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a friction mechanism combining interacting surfaces and actuation/load transfer.');
INSERT INTO "blocks" VALUES(63,'Pulley','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','component','dwm_functional_boundary_v1','One pulley component in a larger belt/cable mechanism.');
INSERT INTO "blocks" VALUES(64,'Belt-Cable Properties','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Atomic material/property configuration component; not a physical manufactured part.');
INSERT INTO "blocks" VALUES(65,'Leadscrew','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents interacting transmission elements, such as a gear pair, planetary set, belt and pulleys, or screw and nut.');
INSERT INTO "blocks" VALUES(66,'Lead Screw Joint','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','component','dwm_functional_boundary_v1','One ideal kinematic coupling component; distinguish from the physical screw-and-nut assembly represented by Leadscrew.');
INSERT INTO "blocks" VALUES(67,'Translational Spring','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(68,'Translational Damper','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(69,'Translational Friction','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(70,'Prismatic Joint','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(71,'Cylindrical Joint','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(72,'Mass','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(73,'Translational Hard Stop','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(74,'Brick Solid','R2025b','introduced_by_R2025b_documented',0,'R2019b','','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(75,'Cylindrical Solid','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(76,'File Solid','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','One rigid-body abstraction regardless of the number of physical parts in imported geometry.');
INSERT INTO "blocks" VALUES(77,'Rigid Transform','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(78,'Weld Joint','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(79,'General Flexible Beam','R2025b','introduced_by_R2025b_documented',0,'R2018b','','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(80,'Ideal Torque Source','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(81,'Spatial Contact Force','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(82,'Single-Acting Actuator (IL)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete fluid actuator combining moving element, chamber(s), housing and force/torque conversion.');
INSERT INTO "blocks" VALUES(83,'Double-Acting Actuator (IL)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete fluid actuator combining moving element, chamber(s), housing and force/torque conversion.');
INSERT INTO "blocks" VALUES(84,'Double-Acting Actuator (G)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete fluid actuator combining moving element, chamber(s), housing and force/torque conversion.');
INSERT INTO "blocks" VALUES(85,'Centrifugal Pump (IL)','R2025b','introduced_by_R2025b_documented',0,'R2020a','','assembly','dwm_functional_boundary_v1','Represents a complete pump with working displacement/impeller mechanism, casing and shaft; internal detail can be abstracted.');
INSERT INTO "blocks" VALUES(86,'Centrifugal Pump (TL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete pump with working displacement/impeller mechanism, casing and shaft; internal detail can be abstracted.');
INSERT INTO "blocks" VALUES(87,'Fixed-Displacement Pump (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete pump with working displacement/impeller mechanism, casing and shaft; internal detail can be abstracted.');
INSERT INTO "blocks" VALUES(88,'Variable-Displacement Pump (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete pump with working displacement/impeller mechanism, casing and shaft; internal detail can be abstracted.');
INSERT INTO "blocks" VALUES(89,'Pressure-Compensated Pump (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete pump with working displacement/impeller mechanism, casing and shaft; internal detail can be abstracted.');
INSERT INTO "blocks" VALUES(90,'Pipe (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(91,'Pipe (TL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(92,'Local Restriction (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(93,'Reservoir (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(94,'Check Valve (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents an assembled valve mechanism combining body, moving flow-control element and operating behavior.');
INSERT INTO "blocks" VALUES(95,'Pressure Relief Valve (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents an assembled valve mechanism combining body, moving flow-control element and operating behavior.');
INSERT INTO "blocks" VALUES(96,'Double-Acting Rotary Actuator (IL)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete fluid actuator combining moving element, chamber(s), housing and force/torque conversion.');
INSERT INTO "blocks" VALUES(97,'4-Way 3-Position Directional Valve (IL)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents an assembled valve mechanism combining body, moving flow-control element and operating behavior.');
INSERT INTO "blocks" VALUES(98,'Compressor (G)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete compressor combining a compression mechanism, casing and drive interface.');
INSERT INTO "blocks" VALUES(99,'Positive-Displacement Compressor (G)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents a complete compressor combining a compression mechanism, casing and drive interface.');
INSERT INTO "blocks" VALUES(100,'Pipe (G)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(101,'Constant Volume Chamber (G)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(102,'Local Restriction (G)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(103,'Reservoir (G)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(104,'Controlled Heat Flow Rate Source','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(105,'Thermal Mass','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(106,'Conductive Heat Transfer','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(107,'Convective Heat Transfer','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(108,'Radiative Heat Transfer','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(109,'Heat Exchanger (TL-TL)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Combines two fluid flow paths and a thermal exchange structure.');
INSERT INTO "blocks" VALUES(110,'Compressor (2P)','R2025b','introduced_by_R2025b_documented',0,'R2022a','','assembly','dwm_functional_boundary_v1','Represents a complete compressor combining a compression mechanism, casing and drive interface.');
INSERT INTO "blocks" VALUES(111,'Positive-Displacement Compressor (2P)','R2025b','introduced_by_R2025b_documented',0,'R2022a','','assembly','dwm_functional_boundary_v1','Represents a complete compressor combining a compression mechanism, casing and drive interface.');
INSERT INTO "blocks" VALUES(112,'Thermostatic Expansion Valve (2P)','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents an assembled valve mechanism combining body, moving flow-control element and operating behavior.');
INSERT INTO "blocks" VALUES(113,'Receiver Accumulator (2P)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(114,'System-Level Refrigeration Cycle (2P)','R2025b','introduced_by_R2025b_documented',0,'R2023a','','assembly','dwm_functional_boundary_v1','Combines compressor, condenser, receiver, expansion device and evaporator into a complete cycle.');
INSERT INTO "blocks" VALUES(115,'Fan (G)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Represents the fan machine and its shaft-to-fluid performance, rather than a single blade.');
INSERT INTO "blocks" VALUES(116,'Fan (MA)','R2025b','introduced_by_R2025b_documented',0,'R2021b','','assembly','dwm_functional_boundary_v1','Represents the fan machine and its shaft-to-fluid performance, rather than a single blade.');
INSERT INTO "blocks" VALUES(117,'Pipe (MA)','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(118,'n-D Lookup Table','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(119,'Integrator','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(120,'Variable Resistor','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(121,'Ideal Force Source','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(122,'Battery','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','component','dwm_functional_boundary_v1','Treated as one lumped battery source at this boundary. A battery pack built from multiple cells would be an assembly; this generic entry does not specify a pack.');
INSERT INTO "blocks" VALUES(123,'Battery (Table-Based)','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','component','dwm_functional_boundary_v1','Treated as one tabulated battery source at this boundary; parameterization can represent a cell or larger battery, so reassess classification for a specific pack.');
INSERT INTO "blocks" VALUES(124,'Battery Equivalent Circuit','R2025b','introduced_by_R2025b_documented',0,'R2023b','','assembly','dwm_functional_boundary_v1','Combines equivalent electrical circuit elements and electrothermal dynamics; classification describes the model assembly, not a claim that the battery is a multi-cell pack.');
INSERT INTO "blocks" VALUES(125,'Solar Cell','R2025b','documentation_reviewed_release_not_individually_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(126,'Solver Configuration','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Atomic model-infrastructure component; not a physical manufactured part.');
INSERT INTO "blocks" VALUES(127,'Simulink-PS Converter','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(128,'PS-Simulink Converter','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(129,'Electrical Reference','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(130,'Mechanical Rotational Reference','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(131,'Mechanical Translational Reference','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(132,'Thermal Reference','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(133,'World Frame','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Individual modeled element or atomic function at the DWM catalog boundary; physical or software internals may contain multiple parts.');
INSERT INTO "blocks" VALUES(134,'Mechanism Configuration','R2025b','candidate_not_individually_release_verified',0,NULL,'','component','dwm_functional_boundary_v1','Atomic model-infrastructure component; not a physical manufactured part.');
INSERT INTO "blocks" VALUES(135,'Subsystem','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Container or reference intended to compose model elements; a particular instance may be empty or contain only one child.');
INSERT INTO "blocks" VALUES(136,'Model','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Container or reference intended to compose model elements; a particular instance may be empty or contain only one child.');
INSERT INTO "blocks" VALUES(137,'Variant Subsystem','R2025b','candidate_not_individually_release_verified',0,NULL,'','assembly','dwm_functional_boundary_v1','Container or reference intended to compose model elements; a particular instance may be empty or contain only one child.');
CREATE TABLE catalog_requirements(id INTEGER PRIMARY KEY, requirement TEXT NOT NULL);
INSERT INTO "catalog_requirements" VALUES(1,'Parameterized CAD, explicit interfaces, and bill of materials per subsystem.');
INSERT INTO "catalog_requirements" VALUES(2,'Manufacturing, assembly, operation, maintenance, and repair instructions.');
INSERT INTO "catalog_requirements" VALUES(3,'Control firmware and simulation models where applicable.');
INSERT INTO "catalog_requirements" VALUES(4,'Operating limits, test procedures, assumptions, and verification evidence.');
INSERT INTO "catalog_requirements" VALUES(5,'Make locally / assemble locally / purchase classification; no classifications assigned yet.');
INSERT INTO "catalog_requirements" VALUES(6,'Qualify food-contact, drinking-water, high-pressure, and high-energy variants separately.');
INSERT INTO "catalog_requirements" VALUES(7,'Use matching fluid-property/settings blocks; fluid domain ports are not interchangeable.');
INSERT INTO "catalog_requirements" VALUES(8,'Do not double-count mass, friction, or screw constraints when coupling 1-D and 3-D models.');
INSERT INTO "catalog_requirements" VALUES(9,'Proposed first module: motor + matched drive + screw/belt transmission + guides + feedback + controller + protective controls.');
INSERT INTO "catalog_requirements" VALUES(10,'No complete process block is claimed for extrusion, cutting, welding, filtration capture, or casting.');
INSERT INTO "catalog_requirements" VALUES(11,'Recommended subsystem interfaces should be sized by requirements; one block family does not imply one physical size.');
CREATE TABLE corrections(id INTEGER PRIMARY KEY, subsystem_id INTEGER REFERENCES subsystems(id), previous_entry TEXT NOT NULL, corrected_entry TEXT NOT NULL, rationale TEXT NOT NULL);
INSERT INTO "corrections" VALUES(1,NULL,'R2011a compatibility caveat','Target MATLAB R2025b','User explicitly specified R2025b; do not assume installed products.');
INSERT INTO "corrections" VALUES(2,11,'Solid','Brick Solid; Cylindrical Solid; File Solid','Use specific geometry blocks.');
INSERT INTO "corrections" VALUES(3,13,'Solid','Brick Solid; Cylindrical Solid; File Solid','Use specific geometry blocks.');
INSERT INTO "corrections" VALUES(4,11,'Spring equivalents','Translational Spring; Rotational Spring; corresponding dampers','Use exact block names.');
INSERT INTO "corrections" VALUES(5,7,'Rigid or lumped shaft only','Add Flexible Cylindrical Beam','R2020a introduction documented.');
INSERT INTO "corrections" VALUES(6,11,'Rigid/lumped frame only','Add General Flexible Beam and Flexible Cylindrical Beam','Both predate R2025b.');
INSERT INTO "corrections" VALUES(7,12,'Rigid/lumped spindle only','Add Flexible Cylindrical Beam','Capture shaft flexibility.');
INSERT INTO "corrections" VALUES(8,24,'Base-Simscape Battery alternatives','Battery and Battery (Table-Based): EE or BAT; Battery Equivalent Circuit: BAT','Correct product ownership.');
INSERT INTO "corrections" VALUES(9,2,'Unversioned converter capabilities','Exclude ENA port and R2026a rectifier conduction-loss feature','Block exists in R2025b; newer options do not.');
INSERT INTO "corrections" VALUES(10,4,'Stateflow Chart','Chart (Stateflow)','Normalize actual block label.');
CREATE TABLE fluid_domains(code TEXT PRIMARY KEY, meaning TEXT NOT NULL);
INSERT INTO "fluid_domains" VALUES('IL','Isothermal liquid');
INSERT INTO "fluid_domains" VALUES('TL','Thermal liquid');
INSERT INTO "fluid_domains" VALUES('G','Gas');
INSERT INTO "fluid_domains" VALUES('MA','Moist air');
INSERT INTO "fluid_domains" VALUES('2P','Two-phase fluid');
CREATE TABLE metadata(key TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT INTO "metadata" VALUES('title','DWM community subsystem and MathWorks block catalog');
INSERT INTO "metadata" VALUES('target_release','R2025b');
INSERT INTO "metadata" VALUES('provenance','User-requested transcription of preceding 25-subsystem list, block mapping, and R2025b corrections.');
INSERT INTO "metadata" VALUES('scope','Engineering reference catalog; not a runtime economy/world-package database or installed block inventory.');
INSERT INTO "metadata" VALUES('verification','No MATLAB execution performed. Candidate entries retain uncertainty; documentation_reviewed records reflect sources examined in the preceding conversation, not an installed R2025b test.');
INSERT INTO "metadata" VALUES('ranking','Proposed reuse/manufacturing priority, not a schedule or permission to defer safety.');
INSERT INTO "metadata" VALUES('product_semantics','Multiple product owners can mean alternative library availability, not that every listed product must be purchased. Base MATLAB/Simulink/Simscape dependencies are not repeated per block.');
INSERT INTO "metadata" VALUES('mapping_semantics','A subsystem maps to candidate components or alternatives. Do not instantiate every block together or double-count inertia, friction, and constraints.');
INSERT INTO "metadata" VALUES('repository_selection','DWMStudio owns engineering workbench/reference data per Dream_World_Maker_Project_Goals.md. Neither inspected default branch had a tracked database directory; Databases is new.');
INSERT INTO "metadata" VALUES('source_repository_commit','cd240a19e73beabe37d6b8d32b3346b5a3e069b3');
INSERT INTO "metadata" VALUES('schema_version','2');
INSERT INTO "metadata" VALUES('classification_basis','dwm_functional_boundary_v1: component = individual modeled element or atomic function; assembly = interacting mechanism, circuit, combined controller, system or composition container. This is DWM editorial modeling classification, not MathWorks implementation metadata or a manufacturing BOM.');
INSERT INTO "metadata" VALUES('classification_scope','Every block has a binary entry_type and rationale. Support/configuration blocks are components. Physical devices may contain parts even when abstracted as a component. Reassess parameterized instances (especially batteries, imported solids and user functions) at the chosen engineering boundary.');
INSERT INTO "metadata" VALUES('classification_provenance','User requested assembly/component classification of existing catalog entries. Assigned from the represented functional boundary; MATLAB runtime and internal block implementation were not inspected.');
CREATE TABLE products(code TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, role TEXT NOT NULL);
INSERT INTO "products" VALUES('MATLAB','MATLAB','base environment');
INSERT INTO "products" VALUES('SL','Simulink','signal modeling and controls');
INSERT INTO "products" VALUES('SC','Simscape','physical modeling foundation');
INSERT INTO "products" VALUES('EE','Simscape Electrical','electrical components');
INSERT INTO "products" VALUES('DL','Simscape Driveline','1-D mechanical power transmission');
INSERT INTO "products" VALUES('MB','Simscape Multibody','3-D mechanisms');
INSERT INTO "products" VALUES('FL','Simscape Fluids','fluid systems');
INSERT INTO "products" VALUES('BAT','Simscape Battery','battery modeling');
INSERT INTO "products" VALUES('SF','Stateflow','state-machine logic');
CREATE TABLE sources(id INTEGER PRIMARY KEY, title TEXT NOT NULL, url TEXT NOT NULL UNIQUE, evidence_type TEXT NOT NULL);
INSERT INTO "sources" VALUES(1,'BLDC','https://www.mathworks.com/help/sps/ref/bldc.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(2,'PMSM','https://www.mathworks.com/help/sps/ref/pmsm.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(3,'Stepper Motor','https://www.mathworks.com/help/sps/ref/steppermotor.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(4,'Induction Machine Squirrel Cage','https://www.mathworks.com/help/sps/ref/inductionmachinesquirrelcage.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(5,'H-Bridge','https://www.mathworks.com/help/sps/ref/hbridge.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(6,'Converter (Three-Phase)','https://www.mathworks.com/help/sps/ref/converterthreephase.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(7,'Average-Value Voltage Source Converter (Three-Phase)','https://www.mathworks.com/help/sps/ref/averagevaluevoltagesourceconverterthreephase.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(8,'BLDC Commutation Logic','https://www.mathworks.com/help/sps/bldc-control.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(9,'BLDC Current Controller with PWM Generation','https://www.mathworks.com/help/sps/ref/bldccurrentcontrollerwithpwmgeneration.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(10,'Belt Drive','https://www.mathworks.com/help/sdl/ref/beltdrive.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(11,'Pulley','https://www.mathworks.com/help/sm/ref/pulley.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(12,'Leadscrew','https://www.mathworks.com/help/sdl/ref/leadscrew.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(13,'Lead Screw Joint','https://www.mathworks.com/help/sm/ref/leadscrewjoint.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(14,'Brick Solid','https://www.mathworks.com/help/sm/ref/bricksolid.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(15,'Flexible Cylindrical Beam','https://www.mathworks.com/help/sm/ref/flexiblecylindricalbeam.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(16,'General Flexible Beam','https://www.mathworks.com/help/sm/ref/generalflexiblebeam.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(17,'Centrifugal Pump (IL)','https://www.mathworks.com/help/hydro/ref/centrifugalpumpil.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(18,'Double-Acting Actuator (IL)','https://www.mathworks.com/help/hydro/ref/doubleactingactuatoril.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(19,'Single-Acting Actuator (IL)','https://www.mathworks.com/help/hydro/ref/singleactingactuatoril.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(20,'Double-Acting Rotary Actuator (IL)','https://www.mathworks.com/help/hydro/ref/doubleactingrotaryactuatoril.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(21,'Double-Acting Actuator (G)','https://www.mathworks.com/help/hydro/ref/doubleactingactuatorg.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(22,'Positive-Displacement Compressor (G)','https://www.mathworks.com/help/hydro/ref/positivedisplacementcompressorg.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(23,'Heat Exchanger (TL-TL)','https://www.mathworks.com/help/hydro/ref/heatexchangertltl.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(24,'Compressor (2P)','https://www.mathworks.com/help/hydro/ref/compressor2p.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(25,'Positive-Displacement Compressor (2P)','https://www.mathworks.com/help/hydro/ref/positivedisplacementcompressor2p.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(26,'System-Level Refrigeration Cycle (2P)','https://www.mathworks.com/help/hydro/ref/systemlevelrefrigerationcycle2p.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(27,'Fan (G)','https://www.mathworks.com/help/hydro/ref/fang.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(28,'Fan (MA)','https://www.mathworks.com/help/hydro/ref/fanma.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(29,'Battery','https://www.mathworks.com/help/sps/ref/battery.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(30,'Battery (Table-Based)','https://www.mathworks.com/help/sps/ref/batterytablebased.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(31,'Battery Equivalent Circuit','https://www.mathworks.com/help/simscape-battery/ref/batteryequivalentcircuit.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(32,'Solar Cell','https://www.mathworks.com/help/sps/ref/solarcell.html','documentation_examined_in_prior_conversation');
INSERT INTO "sources" VALUES(33,'DWM project goals','https://github.com/TSPFounder/DWMStudio/blob/cd240a19e73beabe37d6b8d32b3346b5a3e069b3/Dream_World_Maker_Project_Goals.md','repository_role');
INSERT INTO "sources" VALUES(34,'SQLite handoff architecture','https://github.com/TSPFounder/DWMStudio/blob/cd240a19e73beabe37d6b8d32b3346b5a3e069b3/ARCH.md','storage_context');
CREATE TABLE subsystem_blocks(subsystem_id INTEGER NOT NULL REFERENCES subsystems(id), block_id INTEGER NOT NULL REFERENCES blocks(id), mapping_role TEXT NOT NULL DEFAULT 'candidate_component_or_alternative', PRIMARY KEY(subsystem_id,block_id));
INSERT INTO "subsystem_blocks" VALUES(1,1,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(1,2,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(1,3,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(1,4,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(1,5,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(2,6,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(2,7,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(2,8,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(2,9,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(2,10,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(2,11,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(2,12,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,13,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,14,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,15,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,16,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,17,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,18,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,19,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,20,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,21,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(3,22,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,12,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,23,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,24,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,25,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,26,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,27,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,28,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(4,29,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,30,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,31,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,32,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,33,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,34,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,35,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,36,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,37,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,38,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,39,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,40,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,41,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(5,42,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(6,43,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(6,44,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(6,45,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(6,46,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(6,25,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(6,47,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(6,29,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(7,48,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(7,49,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(7,50,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(7,51,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(7,52,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(7,53,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(7,54,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,55,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,56,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,57,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,58,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,59,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,60,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,61,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,62,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,63,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(8,64,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(9,65,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(9,66,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(9,67,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(9,68,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(9,69,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(10,70,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(10,71,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(10,72,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(10,67,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(10,68,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(10,69,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(10,73,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,74,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,75,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,76,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,77,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,78,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,53,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,54,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,79,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,72,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,67,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,49,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,68,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(11,50,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,1,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,2,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,3,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,4,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,5,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,52,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,54,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,48,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,49,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,50,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(12,80,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,74,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,75,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,76,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,77,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,78,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,70,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,81,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,82,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,83,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(13,84,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,37,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,81,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,30,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,31,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,32,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,33,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,38,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,42,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,41,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,39,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(14,40,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(15,85,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(15,86,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(15,87,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(15,88,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(15,89,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(16,90,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(16,91,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(16,92,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(16,93,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(16,94,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(16,95,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,82,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,83,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,96,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,97,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,87,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,88,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,95,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(17,93,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(18,98,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(18,99,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(18,84,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(18,100,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(18,101,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(18,102,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(18,103,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(19,104,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(19,105,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(19,106,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(19,107,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(19,108,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(19,36,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(19,12,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(20,109,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(20,110,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(20,111,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(20,112,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(20,113,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(20,114,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(21,115,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(21,116,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(21,100,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(21,117,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(21,102,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(21,101,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(21,103,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,1,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,2,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,3,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,4,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,55,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,59,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,104,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,105,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,36,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,28,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,118,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(22,119,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(23,104,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(23,18,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(23,120,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(23,121,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(23,80,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(23,28,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(23,118,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,122,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,123,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,124,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,14,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,15,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,16,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,34,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,35,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,36,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,12,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,23,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(24,29,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,125,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,3,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,5,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,7,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,15,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,8,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,80,'candidate_component_or_alternative');
INSERT INTO "subsystem_blocks" VALUES(25,118,'candidate_component_or_alternative');
CREATE TABLE subsystems(id INTEGER PRIMARY KEY CHECK(id BETWEEN 1 AND 25), name TEXT NOT NULL UNIQUE, components TEXT NOT NULL, applications TEXT NOT NULL, modeling_notes TEXT NOT NULL, target_release TEXT NOT NULL DEFAULT 'R2025b');
INSERT INTO "subsystems" VALUES(1,'Electric motors','BLDC, stepper, brushed DC, induction variants','Pumps, machine tools, food processors, fans, vehicles, agriculture','Choose actual motor technology; servo adds drive, feedback and controller.','R2025b');
INSERT INTO "subsystems" VALUES(2,'Motor drives and controllers','ESCs, stepper drivers, servo drives, VFDs','Controlled speed, torque and positioning','Different drives require different power stages and controls.','R2025b');
INSERT INTO "subsystems" VALUES(3,'Electrical power conversion and distribution','Supplies, DC converters, harnesses, connectors, protection','Workshops, appliances, controls, mobile equipment','Model harness impedance and protection explicitly as appropriate.','R2025b');
INSERT INTO "subsystems" VALUES(4,'Machine controllers','Microcontroller/PLC modules, I/O, communications, operator panels','CNC, irrigation, printers, ovens, process equipment','Behavioral control model; hardware timing is not automatic.','R2025b');
INSERT INTO "subsystems" VALUES(5,'Sensors and feedback','Encoders, limits, temperature, pressure, flow, current, load','Accurate motion, process control, monitoring, faults','Ideal sensors need quantization, noise, delay and calibration for instrumentation realism. Fluid sensors must match domain.','R2025b');
INSERT INTO "subsystems" VALUES(6,'Machine safety and protective controls','E-stop, interlocks, guards, overload protection, shutdown','Every powered machine','Build fault/reset/shutdown logic plus physical switches/brakes. Assertion is a check, not a physical safety device.','R2025b');
INSERT INTO "subsystems" VALUES(7,'Rotary support assemblies','Shafts, bearings, housings, couplings, seals, lubrication','Wheels, spindles, pumps, mixers, turbines, gearboxes','Composite model. Bearing life, lubrication and leakage need added models.','R2025b');
INSERT INTO "subsystems" VALUES(8,'Mechanical transmissions','Gears, reducers, belts, chains, pulleys, brakes, clutches','Match motor speed/torque to loads','Use DL for power transmission or MB for spatial mechanisms; chain compliance/loss may require custom models.','R2025b');
INSERT INTO "subsystems" VALUES(9,'Screw-drive actuators','Lead/ball screws, nuts, supports, motor mounts','CNC axes, tables, positioning, screw presses','Leadscrew includes thread/friction; Lead Screw Joint provides 3-D coupling. Add preload/backlash/compliance as needed; avoid duplicate constraints.','R2025b');
INSERT INTO "subsystems" VALUES(10,'Linear guides and slides','Rails, carriages, bushings, ways, alignment','Routers, lathes, printers, saws, handling','Represent allowed motion, mass, friction, compliance and stops.','R2025b');
INSERT INTO "subsystems" VALUES(11,'Structural frames and machine beds','Bolted, welded, cast, extrusion structures and mounting','Machine tools, benches, carts, farm implements, enclosures','Rigid or flexible beam representation; detailed stress needs structural analysis. Generic Solid and Spring labels replaced by specific blocks.','R2025b');
INSERT INTO "subsystems" VALUES(12,'Spindles and toolholding','Spindles, chucks, collets, arbors, tool interfaces','Drilling, routing, milling, turning, grinding','Composite; cutting torque, imbalance, compliance and chatter require models/data.','R2025b');
INSERT INTO "subsystems" VALUES(13,'Workholding and fixtures','Vises, clamps, pins, jigs, molds, fixture plates','Repeatable machining, welding, assembly, casting','Fixed constraints or contact/actuators. Mold geometry is not casting physics.','R2025b');
INSERT INTO "subsystems" VALUES(14,'Metrology and calibration','Probes, gauges, reference surfaces, alignment, test rigs','Interchangeable parts, accuracy verification','Composite measurement chain with scale, offset, resolution, lag, noise and optional contact.','R2025b');
INSERT INTO "subsystems" VALUES(15,'Liquid pumping','Centrifugal, diaphragm, gear, peristaltic variants','Irrigation, water, coolant, food processing, dosing','Direct generic pump models; diaphragm/peristaltic pulsation may require custom displacement models.','R2025b');
INSERT INTO "subsystems" VALUES(16,'Fluid routing and filtration','Valves, manifolds, pipes, hoses, fittings, strainers, filters','Water, process plumbing, lubrication, coolant','Restriction approximates filter pressure drop; capture/clogging require added state equations.','R2025b');
INSERT INTO "subsystems" VALUES(17,'Hydraulic power and actuation','Power units, cylinders, valves, pressure protection','Presses, lifting, compactors, agricultural implements','Assemble pumps, reservoir, valves, actuators and load; thermal-liquid variants capture temperature.','R2025b');
INSERT INTO "subsystems" VALUES(18,'Pneumatic and vacuum systems','Compressors/vacuum pumps, conditioning, valves, cylinders, grippers','Clamping, handling, packaging, vacuum forming','Use absolute pressure and valid pump maps for vacuum. Suction seal/leak/holding force needs custom model.','R2025b');
INSERT INTO "subsystems" VALUES(19,'Controlled heating','Heaters/burners, insulation, regulation, thermal protection','Ovens, dryers, kilns, furnaces, heat treatment, hot water','Lumped thermal model; combustion, melting, transformations need additional physics.','R2025b');
INSERT INTO "subsystems" VALUES(20,'Cooling and heat transfer','Heat exchangers, coolant loops, refrigeration, insulation','Food preservation, cold storage, heat pumps, machine cooling','Use complete system-level cycle or assemble components with condenser and evaporator.','R2025b');
INSERT INTO "subsystems" VALUES(21,'Air movement and extraction','Fans, blowers, ducts, separators, filtration','Ventilation, crop drying, dust/fume extraction','Airflow/pressure/humidity model; particle separation/collection needs custom equations.','R2025b');
INSERT INTO "subsystems" VALUES(22,'Material feeding and extrusion','Rollers, augers, hoppers, metering, extrusion heads','3-D printers, filament, pellets, food processing','Composite feed/heating/melt-pressure/load model; rheology/conveying/deposition need custom equations.','R2025b');
INSERT INTO "subsystems" VALUES(23,'Cutting and joining process modules','Separate laser, plasma, welding, resistance joining variants','Sheet fabrication, frames, enclosures, repair, tooling','Custom process physics required; Weld Joint is rigid connection, not a welding-process simulation.','R2025b');
INSERT INTO "subsystems" VALUES(24,'Battery storage and charging','Battery modules, BMS, chargers, protective enclosures','Portable tools, carts, backup, renewable storage','Battery and table-based alternatives in EE/BAT, not base SC. Charging/balancing/protection/estimation are additional subsystems.','R2025b');
INSERT INTO "subsystems" VALUES(25,'Renewable-energy conversion','Generators, rectifiers, charge regulation, inverter interfaces','Wind, microhydro, solar infrastructure','Machine operated as generator; wind/water rotor torque and MPPT need their own models.','R2025b');
CREATE TABLE support_blocks(block_id INTEGER PRIMARY KEY REFERENCES blocks(id), purpose TEXT NOT NULL);
INSERT INTO "support_blocks" VALUES(77,'Configure and position Multibody mechanism');
INSERT INTO "support_blocks" VALUES(126,'Solve each distinct physical network');
INSERT INTO "support_blocks" VALUES(127,'Signal/physical-signal interface');
INSERT INTO "support_blocks" VALUES(128,'Signal/physical-signal interface');
INSERT INTO "support_blocks" VALUES(129,'Domain reference as appropriate');
INSERT INTO "support_blocks" VALUES(130,'Domain reference as appropriate');
INSERT INTO "support_blocks" VALUES(131,'Domain reference as appropriate');
INSERT INTO "support_blocks" VALUES(132,'Domain reference as appropriate');
INSERT INTO "support_blocks" VALUES(133,'Configure and position Multibody mechanism');
INSERT INTO "support_blocks" VALUES(134,'Configure and position Multibody mechanism');
INSERT INTO "support_blocks" VALUES(135,'Reusable models with explicit interfaces');
INSERT INTO "support_blocks" VALUES(136,'Reusable models with explicit interfaces');
INSERT INTO "support_blocks" VALUES(137,'Reusable models with explicit interfaces');
CREATE VIEW subsystem_catalog AS SELECT s.id AS priority,s.name AS subsystem,s.components,s.applications,s.modeling_notes,b.name AS block,b.target_release,b.availability_status,b.runtime_tested,b.notes AS block_notes,b.entry_type,b.classification_basis,b.classification_rationale,(SELECT group_concat(p.name, '; ') FROM block_products bp JOIN products p ON p.code=bp.product_code WHERE bp.block_id=b.id) AS products FROM subsystems s JOIN subsystem_blocks sb ON sb.subsystem_id=s.id JOIN blocks b ON b.id=sb.block_id;
COMMIT;
PRAGMA foreign_keys=ON;
